tunnel: controller-tunnel
credentials-file: /Users/admin/.cloudflared/0d0fa415-86c3-4f36-8b10-593d5d8c2340.json

ingress:
  - hostname: controller.qdreigaming.org
    service: http://localhost:3000
  - service: http_status:404