tunnel: controller-tunnel
credentials-file: <PATH_TO_HOME>/.cloudflared/controller-tunnel.json

ingress:
  - hostname: controller.qdreigaming.org
    service: http://localhost:3000
  - service: http_status:404